# Generate table 1 for SVI paper
Table 1 compares the three SVI, their input variables, and ACS Tables

## Description of Program
- program:    tu3svi4_6av1_Table1
- task:       set up table 1
- Version:    2024-04-27
- 2024-04-29 - adding new varname and oSVInsightutting table to make correlation table
- 2024-07-10 - why is disability missing from table? dropped gencatcode < 800 should have been 900
- 2025-04-12 - update for 2020 SVI data
- 2026-04-23 - Replication Check
- project:    DOE Southeast Texas Urban Field Lab SVI Paper - round 4 of analysis 
- funding:	  DOE
- author:    Nathanael Rosenheim
- GRA:        Lidia Mezei

## Control Python
Add install and add packages.

In [18]:
import pandas as pd     # For obtaining and cleaning tabular data
import os # For saving to path

In [19]:
import sys
print("Python Version     ", sys.version)

Python Version      3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]

## Set Provenance

In [20]:
# Get information on current working directory (getcwd)
os.getcwd()

'c:\\Users\\nathanael99\\Box\\SETx-UIFL_Team-folder\\Theme_3_eq\\Text\\SVI_Analysis_Paper\\DesignSafe-Archive\\WorkNPR'

In [21]:
# Store Program Name for oSVInsightut files to have the same name and saved in the same directory
programname = "tu3svi4_6av1_Table1_2026-04-23"
# Make directory to save output
if not os.path.exists(programname):
   os.mkdir(programname)

# Obtain Data
Obtain data from about each variable in SVI data.

In [22]:
varmetadata_df = pd.read_excel("../SourceData/tu3svi2_0av3_SVIdatadictionary_2025-04-08.xlsx",
                            sheet_name="SVI_vars")

In [23]:
varmetadata_df.head()

,SVI,order,year,newvarname,gencat,gencatcode,comcat,comcatcode,theme,SVIcat,label,oldvarname,ACStable1v2,ACStable1v1,inverted,proportion,percent,dtype
0,CDC,10010,2018,C201810010,Geocode,100,TRACT2010,10,NaN,Geocode,Census Tract 11 Digit Geocode,FIPS,NaN,NaN,0,0,0,str
1,CDC,10020,2018,C201810020,Denominator,100,Population,20,NaN,Denominator,Population,E_TOTPOP,S0601,S0601,0,0,0,int64
2,CDC,10030,2018,C201810030,Denominator,100,Households,30,NaN,Denominator,Households,E_HH,DP02,DP02,0,0,0,int64
3,CDC,10040,2018,C201810040,Denominator,100,Housing Units,40,NaN,Denominator,Housing Units,E_HU,DP04,DP04,0,0,0,int64
4,CDC,20010,2018,C201820010,Economic,200,Poverty,10,THEME1,Socioeconomic Status,Below Poverty,EP_POV,S0601,S0601,0,0,1,float

## Clean Data
Need to keep the SVI, gencat, comcat, ACStable1v2v2

In [24]:
# keep columns that are needed
keep_cols = ['SVI', 'year','gencatcode','comcatcode','gencat', 'comcat', 'label', 'ACStable1v2','newvarname']
table1_df = varmetadata_df[keep_cols].copy(deep=True)
# keep if gencatcode equal to or greater than 200 and less than 900
condition1 = table1_df['gencatcode'] >= 100
condition2 = table1_df['gencatcode'] < 900
table1_df = table1_df[condition1 & condition2]

In [25]:
table1_df.head()

,SVI,year,gencatcode,comcatcode,gencat,comcat,label,ACStable1v2,newvarname
0,CDC,2018,100,10,Geocode,TRACT2010,Census Tract 11 Digit Geocode,NaN,C201810010
1,CDC,2018,100,20,Denominator,Population,Population,S0601,C201810020
2,CDC,2018,100,30,Denominator,Households,Households,DP02,C201810030
3,CDC,2018,100,40,Denominator,Housing Units,Housing Units,DP04,C201810040
4,CDC,2018,200,10,Economic,Poverty,Below Poverty,S0601,C201820010

In [26]:
# if comcat is missing replace with the label
condition = table1_df['comcat'].isnull()
table1_df.loc[condition, 'comcat'] = table1_df.loc[condition, 'label']
# Drop 'label' and 'gencatcode' columns
table1_dfv2 = table1_df.drop(columns=['label'])

table1_dfv2.head(20)

,SVI,year,gencatcode,comcatcode,gencat,comcat,ACStable1v2,newvarname
0,CDC,2018,100,10,Geocode,TRACT2010,NaN,C201810010
1,CDC,2018,100,20,Denominator,Population,S0601,C201810020
2,CDC,2018,100,30,Denominator,Households,DP02,C201810030
3,CDC,2018,100,40,Denominator,Housing Units,DP04,C201810040
4,CDC,2018,200,10,Economic,Poverty,S0601,C201820010
5,CDC,2018,200,20,Economic,Unemployed,DP03,C201820020
6,CDC,2018,200,31,Economic,Per Capita Income Past 12 Months,B19301,C201820031
7,CDC,2018,210,10,Education,No High School Diploma,S0601,C201821010
8,CDC,2018,300,10,Age,Aged 65 or Older,S0101,C201830010
9,CDC,2018,330,10,Child care,Single-parent,DP02,C201833010
10,CDC,2018,330,20,Child care,Aged 17 or Younger,B09001,C201833020
11,CDC,2018,600,10,Race,Minority,B01001H,C201860010
12,CDC,2018,620,10,Language,Language Needs,B16005,C201862010
13,CDC,2018,700,10,Housing Type,Mobile Homes,DP04,C201870010
14,CDC,2018,700,20,Housing Type,Population in Group Quarters,B26001,C201870020
15,CDC,2018,700,50,Housing Type,Multi-Unit Structures,DP04,C201870050
16,CDC,2018,700,55,Housing Type,Crowding,DP04,C201870055
17,CDC,2018,720,10,Transportation,No Vehicle,DP04,C201872010
18,CDC,2018,810,10,Other,Civilian With a Disability,DP02,C201881010
26,HRRC,2018,100,10,Geocode,TRACT2010,NaN,H201810010

In [27]:
# Using pivot_table to avoid errors on duplicate 'ACStable1v2' and 'SVI' entries
table1_dfv3 = table1_dfv2.pivot_table(index=['year','gencat','gencatcode','comcatcode','comcat'], columns='SVI', 
                                  values=['ACStable1v2','newvarname'], aggfunc='first')
# Reset the index
table1_dfv3.reset_index(inplace=True)
# sort by gencatcode and comcatcode
table1_dfv3.sort_values(by=['gencatcode','comcatcode'], inplace=True)
# replace missing with blank ''
table1_dfv3.fillna('', inplace=True)
# Display the first few rows of the transformed DataFrame
table1_dfv3.head()

     year       gencat gencatcode comcatcode      comcat ACStable1v2           \
SVI                                                              CDC     HRRC
22   2018      Geocode        100         10   TRACT2010
70   2020      Geocode        100         10   TRACT2020
23   2018      Geocode        100         11      BG2010
71   2020      Geocode        100         11      BG2020
7    2018  Denominator        100         20  Population       S0601  unknown

         newvarname
SVI UTP         CDC        HRRC         UTP
22       C201810010  H201810010  U201810010
70       C202010010  H202010010  U202010010
23                   H201810011  U201810011
71                   H202010011  U202010011
7        C201810020  H201810020

In [28]:
# rename columns and reset so only one level
table1_dfv3.columns = [' '.join(col).strip() for col in table1_dfv3.columns.values]
table1_dfv3.reset_index(drop=True, inplace=True)
table1_dfv3.head()

,year,gencat,gencatcode,comcatcode,comcat,ACStable1v2 CDC,ACStable1v2 HRRC,ACStable1v2 UTP,newvarname CDC,newvarname HRRC,newvarname UTP
0,2018,Geocode,100,10,TRACT2010,,,,C201810010,H201810010,U201810010
1,2020,Geocode,100,10,TRACT2020,,,,C202010010,H202010010,U202010010
2,2018,Geocode,100,11,BG2010,,,,,H201810011,U201810011
3,2020,Geocode,100,11,BG2020,,,,,H202010011,U202010011
4,2018,Denominator,100,20,Population,S0601,unknown,,C201810020,H201810020,

In [29]:
# list columns
table1_dfv3.columns

Index(['year', 'gencat', 'gencatcode', 'comcatcode', 'comcat',
       'ACStable1v2 CDC', 'ACStable1v2 HRRC', 'ACStable1v2 UTP',
       'newvarname CDC', 'newvarname HRRC', 'newvarname UTP'],
      dtype='object')

### Fix some known issues
- HRRC does not actually use Median Home Value in SVI.
- HRRC does not actually use Rent Burden in SVI.
- HRRC uses table 25033 for renter households

In [30]:
# for HRRC Median Home Value replace B25077 with ''
condition = table1_dfv3['ACStable1v2 HRRC'] == 'B25077'
table1_dfv3.loc[condition, 'ACStable1v2 HRRC'] = ''

# for rent burden replace B25070 with ''
condition = table1_dfv3['ACStable1v2 HRRC'] == 'B25070'
table1_dfv3.loc[condition, 'ACStable1v2 HRRC'] = ''

In [31]:
table1_dfv3.head()

,year,gencat,gencatcode,comcatcode,comcat,ACStable1v2 CDC,ACStable1v2 HRRC,ACStable1v2 UTP,newvarname CDC,newvarname HRRC,newvarname UTP
0,2018,Geocode,100,10,TRACT2010,,,,C201810010,H201810010,U201810010
1,2020,Geocode,100,10,TRACT2020,,,,C202010010,H202010010,U202010010
2,2018,Geocode,100,11,BG2010,,,,,H201810011,U201810011
3,2020,Geocode,100,11,BG2020,,,,,H202010011,U202010011
4,2018,Denominator,100,20,Population,S0601,unknown,,C201810020,H201810020,

### Add extra rows

In [32]:
# raname columns
table1_dfv3.rename(columns={'gencat':'General Category',
                            'comcat':'Common Category',
                            'ACStable1v2 CDC':'CDC',
                            'ACStable1v2 HRRC':'HRRC',
                            'ACStable1v2 UTP':'SVInsight',
                            'match':'Match'}, inplace=True)

In [33]:
table1_dfv3.head()

,year,General Category,gencatcode,comcatcode,Common Category,CDC,HRRC,SVInsight,newvarname CDC,newvarname HRRC,newvarname UTP
0,2018,Geocode,100,10,TRACT2010,,,,C201810010,H201810010,U201810010
1,2020,Geocode,100,10,TRACT2020,,,,C202010010,H202010010,U202010010
2,2018,Geocode,100,11,BG2010,,,,,H201810011,U201810011
3,2020,Geocode,100,11,BG2020,,,,,H202010011,U202010011
4,2018,Denominator,100,20,Population,S0601,unknown,,C201810020,H201810020,

## Save results

In [34]:
# save results as a csv
table1_dfv3.to_csv(f"{programname}/{programname}.csv", index=False)