# Create tables for each tract and block group with all variables
In section 5.1 need to report specific numbers for each indicator. Selected numbers will be reported in the text.

## Description of Program
- program:    tu3svi4_6cv1_Phase1Text
- task:       Set up table for published paper
- Version:   
- 2025-04-24: Generate numbers for text 
- 2025-11-06: Check missing and interpolated observations
- 2026-02-15: Adding details on 2020 Response Rates
- 2026-04-23: Replication Check
- project:    DOE Southeast Texas Urban Field Lab SVI Paper - round 4 of analysis 
- funding:	  DOE
- author:    Nathanael Rosenheim
- GRA:        Lidia Mezei

## Control Python
Add install and add packages.

In [1]:
import pandas as pd     # For obtaining and cleaning tabular data
import geopandas as gpd # For obtaining and cleaning spatial data
import numpy as np      # For working with arrays
import geopandas as gpd # For working with spatial data
import matplotlib.pyplot as plt # For plotting
import requests # For obtaining data from APIs
import os # For saving to path

In [2]:
import sys
print("Python Version     ", sys.version)
print("geopandas version: ", gpd.__version__)

Python Version      3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
geopandas version:  1.1.1

## Set Provenance

In [3]:
# Get information on current working directory (getcwd)
os.getcwd()

'c:\\Users\\nathanael99\\Box\\SETx-UIFL_Team-folder\\Theme_3_eq\\Text\\SVI_Analysis_Paper\\DesignSafe-Archive\\WorkNPR'

In [4]:
# Store Program Name for SVInsightut files to have the same name and saved in the same directory
programname = "tu3svi4_6cv3_Phase1Text_2026-04-23"
# Make directory to save output
if not os.path.exists(programname):
   os.mkdir(programname)

# Obtain Data
Obtain data from about each variable in SVI data.

In [5]:
# read in original Version 1 data
sourceprogram = "tu3svi4_2av2_SVIoptions_2026-04-23"
sourcefile = sourceprogram+"/"+sourceprogram+"_all_vars_tract2020.csv"
# read in file and set ids as strings
Tract_df = pd.read_csv(sourcefile, dtype={'TRACT2020':str}, low_memory=False)

sourcefile = sourceprogram+"/"+sourceprogram+"_all_vars_bg2020.csv"
BG_df = pd.read_csv(sourcefile, dtype={'TRACT2020':str, 'BG2020': str}, low_memory=False)

In [6]:
Tract_df.head()

,TRACT2020,ALAND,AWATER,U202020010,U202020013,U202020020,U202020031,U202020033,U202020040,U202020070,...,H202081011,H202090012,H202090093,H202091012,H202091093,H202092021,SETX,FIPSCNTY,airsite_tract,airsite_name
0,48189950200,6306913,0,0.26355,0.29075,0.05352,-15052.0,-0.00000,-59500.0,537.0,...,0.36285,97.0,0.844,4.0,4.0,1.0,0.0,48189.0,0.0,NaN
1,48219950400,12691656,5302,0.21368,0.40714,0.10448,-16492.0,-0.00000,-43800.0,637.0,...,0.29107,93.6,0.796,4.0,4.0,1.0,0.0,48219.0,0.0,NaN
2,48219950300,12186639,0,0.23184,0.27081,0.05693,-26892.0,-0.02171,-98500.0,860.0,...,0.12183,74.7,0.643,3.0,3.0,1.0,0.0,48219.0,0.0,NaN
3,48219950100,214157569,0,0.13342,0.36347,0.08676,-20890.0,-0.01476,-60200.0,616.0,...,0.28967,80.9,0.686,4.0,4.0,1.0,0.0,48219.0,0.0,NaN
4,48219950600,358638163,0,0.11713,0.31648,0.01074,-34403.0,-0.09363,-97100.0,814.0,...,0.18914,40.9,0.445,2.0,2.0,1.0,0.0,48219.0,0.0,NaN

In [7]:
BG_df.head()

,BG2020,ALAND,AWATER,U202020010,U202020013,U202020020,U202020031,U202020033,U202020040,U202020070,...,H202090012,H202090093,H202091012,H202091093,H202092021,SETX,FIPSCNTY,TRACT2020,airsite_bg,airsite_name
0,481539506003,9238641,0,0.12273,0.59882,0.02113,-41060.0,-0.02360,-73300.0,3501.0,...,72.0,0.613,3.0,3.0,1.0,0.0,48153.0,48153950600,0.0,NaN
1,481539506005,1070676551,101332,0.33274,0.08228,0.00000,-22793.0,-0.06962,-163500.0,663.0,...,22.6,0.334,1.0,1.0,1.0,0.0,48153.0,48153950600,0.0,NaN
2,481610004001,12766486,8204,0.30405,0.36973,0.05444,-17938.0,-0.00000,-78900.0,727.0,...,82.9,0.689,4.0,4.0,1.0,0.0,48161.0,48161000400,0.0,NaN
3,481610006001,153883256,544987,0.00000,0.50709,0.00000,-27873.0,-0.14894,-153900.0,661.0,...,27.6,0.365,2.0,2.0,1.0,0.0,48161.0,48161000600,0.0,NaN
4,481759602001,391287006,1789495,0.18392,0.56607,0.01743,-32928.0,-0.07495,-157900.0,393.0,...,53.0,0.502,3.0,3.0,1.0,0.0,48175.0,48175960200,0.0,NaN

In [8]:
# read in table 1 details
sourceprogram = "tu3svi4_6av1_Table1_2026-04-23"
sourcefile = sourceprogram+"/"+sourceprogram+".csv"
table1_df = pd.read_csv(sourcefile)
table1_df.head()

,year,General Category,gencatcode,comcatcode,Common Category,CDC,HRRC,SVInsight,newvarname CDC,newvarname HRRC,newvarname UTP
0,2018,Geocode,100,10,TRACT2010,NaN,NaN,NaN,C201810010,H201810010,U201810010
1,2020,Geocode,100,10,TRACT2020,NaN,NaN,NaN,C202010010,H202010010,U202010010
2,2018,Geocode,100,11,BG2010,NaN,NaN,NaN,NaN,H201810011,U201810011
3,2020,Geocode,100,11,BG2020,NaN,NaN,NaN,NaN,H202010011,U202010011
4,2018,Denominator,100,20,Population,S0601,unknown,NaN,C201810020,H201810020,NaN

In [9]:
# interpolated missing values for SVInsight
sourcefile = "../SourceData/UT_Preisser_SVI/Preisser_SV_Data_2024-08-26/Texas/Data/Texas_2020_tract_missing_values.csv"
# read in CSV file - the first row is not the header
SVInsight_missing_df = pd.read_csv(sourcefile, header=None, low_memory=False)
# rename columns
SVInsight_missing_df.columns = ['TRACT2020', 'Variable', 'Interpolated']
# make TRACT2020 string
SVInsight_missing_df['TRACT2020'] = SVInsight_missing_df['TRACT2020'].astype(str)
# show head
SVInsight_missing_df.head()

     TRACT2020     Variable  Interpolated
0  48005000103  B25064_001E  Interpolated
1  48007950101  B25064_001E  Interpolated
2  48007950103  B25064_001E  Interpolated
3  48007950103  B25077_001E  Interpolated
4  48007950501  B25064_001E  Interpolated

In [10]:
# interpolated missing values for SVInsight
sourcefile = "../SourceData/UT_Preisser_SVI/Preisser_SV_Data_2024-08-26/Texas/Data/Texas_2020_bg_missing_values.csv"
# read in CSV file - the first row is not the header
SVInsight_missing_bg_df = pd.read_csv(sourcefile, header=None, low_memory=False)
# rename columns
SVInsight_missing_bg_df.columns = ['BG2020', 'Variable', 'Interpolated']
# make BG2020 string
SVInsight_missing_bg_df['BG2020'] = SVInsight_missing_bg_df['BG2020'].astype(str)
# show head
SVInsight_missing_bg_df.head()

         BG2020     Variable  Interpolated
0  480019506003  B25064_001E  Interpolated
1  480019506003  B25077_001E  Interpolated
2  480019508001  B25077_001E  Interpolated
3  480019508005  B25064_001E  Interpolated
4  480019509011  B25064_001E  Interpolated

## Clean data

In [11]:
# rename newvarname UTP = newvarname SVInsight
table1_df.rename(columns={'newvarname UTP': 'newvarname SVInsight'}, inplace=True)
table1_df.head()

,year,General Category,gencatcode,comcatcode,Common Category,CDC,HRRC,SVInsight,newvarname CDC,newvarname HRRC,newvarname SVInsight
0,2018,Geocode,100,10,TRACT2010,NaN,NaN,NaN,C201810010,H201810010,U201810010
1,2020,Geocode,100,10,TRACT2020,NaN,NaN,NaN,C202010010,H202010010,U202010010
2,2018,Geocode,100,11,BG2010,NaN,NaN,NaN,NaN,H201810011,U201810011
3,2020,Geocode,100,11,BG2020,NaN,NaN,NaN,NaN,H202010011,U202010011
4,2018,Denominator,100,20,Population,S0601,unknown,NaN,C201810020,H201810020,NaN

# Explore Results

### Create table 1 with variable values for each tract and block group in study sites

In [12]:
# for table 1 keep only year = 2020
condition = table1_df['year'] == 2020
table1_df_v2 = table1_df[condition]
# keep columns with new varname
keep_cols = ['Common Category', 'newvarname CDC', 'newvarname HRRC', 'newvarname SVInsight']
table1_df_v2 = table1_df_v2[keep_cols]
# rename columns
table1_df_v2.rename(columns={'newvarname CDC': 'CDC',
                            'newvarname HRRC': 'HRRC',
                            'newvarname SVInsight': 'SVInsight'}, inplace=True)
# fill missing values with empty string
table1_df_v2.fillna('', inplace=True)
# drop first two rows - do not need TRACT and BG ids
condition = table1_df_v2['Common Category'] == 'TRACT2020'
table1_df_v2 = table1_df_v2[~condition]
condition = table1_df_v2['Common Category'] == 'BG2020'
table1_df_v2 = table1_df_v2[~condition]
table1_df_v2 = table1_df_v2.reset_index(drop=True)
table1_df_v2

,Common Category,CDC,HRRC,SVInsight
0,Population,C202010020,H202010020,
1,Households,C202010030,H202010030,
2,Housing Units,C202010040,,
3,Poverty,C202020010,H202020010,U202020010
4,Elder Households in Poverty,,H202020012,
5,Households with Social Security Income,,,U202020013
6,Unemployed,C202020020,H202020020,U202020020
7,Housing Cost Burden,C202020031,,
8,Per Capita Income Past 12 Months,,,U202020031
9,Percent Households Earning Over $200K,,,U202020033
10,Median Home Value,,H202020040,U202020040
11,No Insurance,C202020050,,U202020050
12,Median Gross Rent,,,U202020070
13,No High School Diploma,C202021010,H202021010,U202021010
14,Aged 65 or Older,C202030010,,
15,Elder Households,,H202030011,
16,Population Under 5 and Over 65,,,U202030020
17,Median Age,,,U202030030
18,Single-parent,C202033010,H202033010,U202033010
19,Aged 17 or Younger,C202033020,,
20,Children Under 5 Years Population,,H202033025,
21,Minority,C202060010,H202060010,
22,"Native American, not Hispanic",,,U202060021
23,"African American, not Hispanic",,,U202060022
24,"Asian, not Hispanic",,,U202060023
25,Hispanic,,,U202060024
26,Language Needs,C202062010,H202062010,U202062010
27,Population that is Female,,,U202065010
28,Female Led Households,,,U202065015
29,Females in the Workforce,,,U202065017
30,Mobile Homes,C202070010,H202070010,U202070010
31,Population in Group Quarters,C202070020,H202070020,
32,Vacant Housing Units,,H202070030,U202070030
33,Renter Households,,H202070040,U202070040
34,Multi-Unit Structures,C202070050,,
35,Crowding,C202070055,,
36,Average Household Size (People Per Unit),,,U202070060
37,Housing Units Older Than 20 Years,,H202070070,
38,No Vehicle,C202072010,H202072010,U202072010
39,Public Transportation Dependent Households,,H202072020,
40,Civilian With a Disability,C202081010,,
41,No Broadband Internet Access Households,,H202081011,
42,Percent Population in Service Jobs,,,U202081021
43,Percent Population in Construction Jobs,,,U202081022
44,Gross Rent Greater Than 30 Percent Income,,H202081030,

In [13]:
# show count of observations by airsite_name
Tract_df['airsite_name'].value_counts()

airsite_name
W2    1
E1    1
E2    1
W1    1
Name: count, dtype: int64

In [14]:
airsite_names = {}
airsite_names['Tract_df'] = Tract_df['airsite_name'].unique().tolist()
airsite_names['Tract_df'] = [x for x in airsite_names['Tract_df'] if str(x) != 'nan']
airsite_names['BG_df'] = BG_df['airsite_name'].unique().tolist()
airsite_names['BG_df'] = [x for x in airsite_names['BG_df'] if str(x) != 'nan']
airsite_names['BG_df'] = sorted(airsite_names['BG_df'])
airsite_names['Tract_df'] = sorted(airsite_names['Tract_df'])
airsite_names['Tract_df']

['E1', 'E2', 'W1', 'W2']

In [15]:
# select if airsite_name is in airsite_names
# for tract
condition = Tract_df['airsite_name'].isin(airsite_names['Tract_df'])
Tract_df[['TRACT2020','airsite_name']][condition].head()

        TRACT2020 airsite_name
1382  48245005900           W2
1438  48245006600           E1
2283  48245010600           E2
3862  48245005100           W1

In [16]:
airsite_names['BG_df']

['E1.1', 'E2.1', 'W1.1', 'W1.2', 'W2.1', 'W2.2']

In [17]:
# loop over table 1 and replace value in cells with value for column in Tract_df
table1_df_v3 = table1_df_v2.copy(deep=True)

dfs = {}
dfs['Tract_df'] = Tract_df.copy(deep=True)
dfs['BG_df'] = BG_df.copy(deep=True)
# loop over dataframes
for key in dfs.keys():
    # loop over airsite names
    for airsite_name in airsite_names[key]:
        # select row from Tract_df where airsite_name is first in list
        condition = dfs[key]['airsite_name'] == airsite_name
        select_df = dfs[key][condition]
        # loop over SVI options
        for option in ['CDC','HRRC','SVInsight']:
            # create new column in table 2
            new_colname = option+" "+airsite_name
            table1_df_v3[new_colname] = ''
            # loop over rows in table 1
            for i in range(len(table1_df_v2)):
                # get the column name from table 1
                colname = table1_df_v2.iloc[i][option]

                if colname != '':
                    #print(colname)

                    # find value in column from Tract_df_airsite
                    try:
                        # get the value for the column name
                        value = select_df.iloc[0][colname]
                        # convert value into formatted string
                        # if value is less than or equal to 1, format as float with 3 decimal places
                        if value <= 1:
                            value = f"{value:,.3f}"
                        # if value is greater than 1, format as float with 0 decimal places
                        elif value > 1:
                            value = f"{value:,.0f}"
                        else:
                            value = str(value)
                        #print("Value: ", value)
                        # replace the value in the column with the value from table 1
                        table1_df_v3.loc[i, new_colname] = value
                    except KeyError:
                        # if the column name is not in Tract_df_airsite, set value to empty string
                        value = 'KeyError'
                        #print("KeyError: ", colname)

In [18]:
table1_df_v3

,Common Category,CDC,HRRC,SVInsight,CDC E1,HRRC E1,SVInsight E1,CDC E2,HRRC E2,SVInsight E2,...,SVInsight W1.1,CDC W1.2,HRRC W1.2,SVInsight W1.2,CDC W2.1,HRRC W2.1,SVInsight W2.1,CDC W2.2,HRRC W2.2,SVInsight W2.2
0,Population,C202010020,H202010020,,"3,908","3,908",,"5,633","5,633",,...,,,507,,,"1,110",,,349,
1,Households,C202010030,H202010030,,"1,597","1,597",,"1,968","1,968",,...,,,201,,,439,,,162,
2,Housing Units,C202010040,,,"2,070",,,"2,156",,,...,,,,,,,,,,
3,Poverty,C202020010,H202020010,U202020010,0.655,0.392,0.392,0.289,0.104,0.104,...,0.346,,0.071,0.071,,0.359,0.359,,0.825,0.825
4,Elder Households in Poverty,,H202020012,,,0.022,,,0.020,,...,,,0.000,,,0.011,,,0.000,
5,Households with Social Security Income,,,U202020013,,,0.178,,,0.402,...,0.579,,,0.507,,,0.317,,,0.019
6,Unemployed,C202020020,H202020020,U202020020,0.114,0.114,0.114,0.040,0.040,0.040,...,0.103,,0.000,0.000,,0.140,0.140,,0.096,0.096
7,Housing Cost Burden,C202020031,,,0.356,,,0.216,,,...,,,,,,,,,,
8,Per Capita Income Past 12 Months,,,U202020031,,,"-14,890.000",,,"-25,694.000",...,"-30,742.000",,,"-17,654.000",,,"-19,191.000",,,"-5,921.000"
9,Percent Households Earning Over $200K,,,U202020033,,,-0.000,,,-0.016,...,-0.040,,,-0.000,,,-0.034,,,-0.000
10,Median Home Value,,H202020040,U202020040,,"84,200","-84,200.000",,"117,400","-117,400.000",...,"-64,806.000",,"39,700","-26,700.000",,"130,300","-82,500.000",,-1.000,"-59,999.000"
11,No Insurance,C202020050,,U202020050,0.311,,0.311,0.257,,0.257,...,0.183,,,0.183,,,0.252,,,0.252
12,Median Gross Rent,,,U202020070,,,452,,,992,...,684,,,969,,,479,,,477
13,No High School Diploma,C202021010,H202021010,U202021010,0.348,0.348,0.348,0.106,0.106,0.106,...,0.046,,0.120,0.120,,0.108,0.108,,0.434,0.434
14,Aged 65 or Older,C202030010,,,0.085,,,0.202,,,...,,,,,,,,,,
15,Elder Households,,H202030011,,,0.167,,,0.312,,...,,,0.468,,,0.239,,,0.019,
16,Population Under 5 and Over 65,,,U202030020,,,0.722,,,0.749,...,0.853,,,0.684,,,0.572,,,0.659
17,Median Age,,,U202030030,,,26,,,39,...,58,,,47,,,33,,,25
18,Single-parent,C202033010,H202033010,U202033010,0.206,0.216,0.532,0.041,0.086,0.229,...,1.000,,0.134,0.794,,0.333,0.825,,0.438,1.000
19,Aged 17 or Younger,C202033020,,,0.360,,,0.216,,,...,,,,,,,,,,
20,Children Under 5 Years Population,,H202033025,,,0.118,,,0.050,,...,,,0.012,,,0.000,,,0.109,
21,Minority,C202060010,H202060010,,0.887,0.887,,0.387,0.387,,...,,,1.000,,,0.944,,,1.000,
22,"Native American, not Hispanic",,,U202060021,,,0.000,,,0.000,...,0.000,,,0.000,,,0.008,,,0.000
23,"African American, not Hispanic",,,U202060022,,,0.438,,,0.057,...,0.955,,,0.966,,,0.894,,,0.989
24,"Asian, not Hispanic",,,U202060023,,,0.066,,,0.074,...,0.000,,,0.000,,,0.000,,,0.000
25,Hispanic,,,U202060024,,,0.381,,,0.239,...,0.000,,,0.000,,,0.000,,,0.011
26,Language Needs,C202062010,H202062010,U202062010,0.146,0.146,0.146,0.030,0.030,0.030,...,0.000,,0.000,0.000,,0.000,0.000,,0.013,0.013
27,Population that is Female,,,U202065010,,,0.519,,,0.497,...,0.540,,,0.471,,,0.469,,,0.542
28,Female Led Households,,,U202065015,,,0.217,,,0.086,...,0.429,,,0.348,,,0.298,,,0.438
29,Females in the Workforce,,,U202065017,,,0.504,,,0.428,...,0.507,,,0.457,,,0.641,,,0.404
30,Mobile Homes,C202070010,H202070010,U202070010,0.017,0.017,0.017,0.009,0.009,0.009,...,0.000,,0.000,0.000,,0.009,0.009,,0.000,0.000
31,Population in Group Quarters,C202070020,H202070020,,0.000,0.000,,0.015,0.015,,...,,,0.000,,,0.000,,,0.000,
32,Vacant Housing Units,,H202070030,U202070030,,0.229,0.229,,0.087,0.087,...,0.320,,0.332,0.332,,0.224,0.224,,0.138,0.138
33,Renter Households,,H202070040,U202070040,,0.554,0.568,,0.311,0.288,...,0.138,,0.093,0.129,,0.630,0.503,,0.968,0.932
34,Multi-Unit Structures,C202070050,,,0.095,,,0.012,,,...,,,,,,,,,,
35,Crowding,C202070055,,,0.072,,,0.051,,,...,,,,,,,,,,
36,Average Household Size (People Per Unit),,,U202070060,,,2,,,3,...,2,,,3,,,3,,,2
37,Housing Units Older Than 20 Years,,H202070070,,,0.820,,,0.874,,...,,,0.900,,,0.760,,,0.920,
38,No Vehicle,C202072010,H202072010,U202072010,0.244,0.244,0.244,0.015,0.015,0.015,...,0.138,,0.119,0.119,,0.303,0.303,,0.667,0.667
39,Public Transportation Dependent Households,,H202072020,,,0.000,,,0.000,,...,,,0.000,,,0.135,,,0.000,
40,Civilian With a Disability,C202081010,,,0.129,,,0.132,,,...,,,,,,,,,,
41,No Broadband Internet Access Households,,H202081011,,,0.394,,,0.067,,...,,,0.413,,,0.180,,,0.389,
42,Percent Population in Service Jobs,,,U202081021,,,0.209,,,0.162,...,0.526,,,0.288,,,0.275,,,0.426
43,Percent Population in Construction Jobs,,,U202081022,,,0.236,,,0.111,...,0.000,,,0.101,,,0.087,,,0.000
44,Gross Rent Greater Than 30 Percent Income,,H202081030,,,,,,,,...,,,,,,,,,,

In [19]:
# save table1_df_v3 to csv
outputfile = programname+"/"+programname+".csv"
table1_df_v3.to_csv(outputfile, index=False)

## Check missing observations

In [20]:
condition1 = Tract_df['C202090012'].isnull()
condition2 = Tract_df['SETX'] == 1
# how many obeservations meet condition1
print("Tracts missing CDC SVI:", condition1.sum())
# how many observations meet condition 1 and condition2
print("Tracts missing CDC SVI and in SETX:", (condition1 & condition2).sum())

Tracts missing CDC SVI: 68
Tracts missing CDC SVI and in SETX: 3

In [21]:
Tract_df[['TRACT2020', 'C202090012','H202090012','U202090012','C202010020','C202010030','SETX']][condition1 & condition2]

,TRACT2020,C202090012,H202090012,U202090012,C202010020,C202010030,SETX
2181,48245980200,NaN,0.8,NaN,6961.0,0.0,1.0
2182,48245980300,NaN,0.9,NaN,3052.0,0.0,1.0
6575,48245980000,NaN,0.0,NaN,0.0,0.0,1.0

In [22]:
6961.0+3052.0

10013.0

In [23]:
condition1 = Tract_df['H202090012'].isnull()
condition2 = Tract_df['SETX'] == 1
# how many obeservations meet condition1
print("Tracts missing HRRC SVI:", condition1.sum())
# how many observations meet condition 1 and condition2
print("Tracts missing HRRC SVI and in SETX:", (condition1 & condition2).sum())

Tracts missing HRRC SVI: 12
Tracts missing HRRC SVI and in SETX: 0

In [24]:
Tract_df[['TRACT2020', 'C202090012','H202090012','U202090012','C202010020','C202010030','SETX']][condition1]

,TRACT2020,C202090012,H202090012,U202090012,C202010020,C202010030,SETX
855,48167990000,NaN,NaN,NaN,NaN,NaN,NaN
1141,48355990000,NaN,NaN,NaN,NaN,NaN,NaN
1182,48245990000,NaN,NaN,NaN,NaN,NaN,NaN
1345,48321990000,NaN,NaN,NaN,NaN,NaN,NaN
1380,48061990000,NaN,NaN,NaN,NaN,NaN,NaN
1662,48071990000,NaN,NaN,NaN,NaN,NaN,NaN
1755,48039990000,NaN,NaN,NaN,NaN,NaN,NaN
2028,48007990000,NaN,NaN,NaN,NaN,NaN,NaN
4695,48261990000,NaN,NaN,NaN,NaN,NaN,NaN
6330,48057990000,NaN,NaN,NaN,NaN,NaN,NaN
6593,48489990000,NaN,NaN,NaN,NaN,NaN,NaN
6812,48273990000,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
condition1 = Tract_df['U202090012'].isnull()
condition2 = Tract_df['SETX'] == 1
# how many obeservations meet condition1
print("Tracts missing SVInsight SVI:", condition1.sum())
# how many observations meet condition 1 and condition2
print("Tracts missing SVInsight SVI and in SETX:", (condition1 & condition2).sum())

Tracts missing SVInsight SVI: 71
Tracts missing SVInsight SVI and in SETX: 3

In [26]:
# merge SETX variable with SVInsight_missing_df
SVInsight_missing_df = SVInsight_missing_df.merge(Tract_df[['TRACT2020','SETX']], on='TRACT2020', how='left')
SVInsight_missing_df.head()

     TRACT2020     Variable  Interpolated  SETX
0  48005000103  B25064_001E  Interpolated   0.0
1  48007950101  B25064_001E  Interpolated   0.0
2  48007950103  B25064_001E  Interpolated   0.0
3  48007950103  B25077_001E  Interpolated   0.0
4  48007950501  B25064_001E  Interpolated   0.0

In [27]:
# show unique values from variable in SVInsight_missing_df
SVInsight_missing_df['Variable'].unique()

array(['B25064_001E', 'B25077_001E'], dtype=object)

In [28]:
# how many SETX tracts have missing SVInsight variables
condition = SVInsight_missing_df['SETX'] == 1
SVInsight_missing_df[condition]

       TRACT2020     Variable  Interpolated  SETX
499  48245000314  B25064_001E  Interpolated   1.0
500  48245011402  B25064_001E  Interpolated   1.0
579  48351950300  B25064_001E  Interpolated   1.0
585  48361021503  B25064_001E  Interpolated   1.0
586  48361021901  B25064_001E  Interpolated   1.0

In [29]:
condition1 = BG_df['H202090012'].isnull()
condition2 = BG_df['SETX'] == 1
# how many obeservations meet condition1
print("Block groups missing HRRC SVI:", condition1.sum())
# how many observations meet condition 1 and condition2
print("Block groups missing HRRC SVI and in SETX:", (condition1 & condition2).sum())

Block groups missing HRRC SVI: 12
Block groups missing HRRC SVI and in SETX: 0

In [30]:
condition1 = BG_df['U202090012'].isnull()
condition2 = BG_df['SETX'] == 1
# how many obeservations meet condition1
print("Block groups missing SVInsight SVI:", condition1.sum())
# how many observations meet condition 1 and condition2
print("Block groups missing SVInsight SVI and in SETX:", (condition1 & condition2).sum())

Block groups missing SVInsight SVI: 220
Block groups missing SVInsight SVI and in SETX: 3

In [31]:
# merge SETX variable with SVInsight_missing_df
SVInsight_missing_bg_df = SVInsight_missing_bg_df.merge(BG_df[['BG2020','SETX','airsite_bg','airsite_name']], on='BG2020', how='left')
SVInsight_missing_bg_df.head()

         BG2020     Variable  Interpolated  SETX  airsite_bg airsite_name
0  480019506003  B25064_001E  Interpolated   0.0         0.0          NaN
1  480019506003  B25077_001E  Interpolated   0.0         0.0          NaN
2  480019508001  B25077_001E  Interpolated   0.0         0.0          NaN
3  480019508005  B25064_001E  Interpolated   0.0         0.0          NaN
4  480019509011  B25064_001E  Interpolated   0.0         0.0          NaN

In [32]:
# show unique values from variable in SVInsight_missing_df
SVInsight_missing_bg_df['Variable'].unique()

array(['B25064_001E', 'B25077_001E', 'B01002_001E'], dtype=object)

In [33]:
# how many SETX tracts have missing SVInsight variables
condition = SVInsight_missing_bg_df['SETX'] == 1
SVInsight_missing_bg_df[condition]

            BG2020     Variable  Interpolated  SETX  airsite_bg airsite_name
3120  481990301001  B25064_001E  Interpolated   1.0         0.0          NaN
3121  481990301002  B25064_001E  Interpolated   1.0         0.0          NaN
3122  481990301002  B25077_001E  Interpolated   1.0         0.0          NaN
3123  481990301003  B25064_001E  Interpolated   1.0         0.0          NaN
3124  481990302003  B25064_001E  Interpolated   1.0         0.0          NaN
...            ...          ...           ...   ...         ...          ...
5768  483610223022  B25064_001E  Interpolated   1.0         0.0          NaN
5769  483610224001  B25064_001E  Interpolated   1.0         0.0          NaN
5770  483610224003  B25077_001E  Interpolated   1.0         0.0          NaN
5771  483610224004  B25064_001E  Interpolated   1.0         0.0          NaN
7505  483519501001  B25064_001E  Tract Filled   1.0         0.0          NaN

[173 rows x 6 columns]

In [34]:
# how many SETX tracts have missing SVInsight variables
condition = SVInsight_missing_bg_df['airsite_bg'] == 1
SVInsight_missing_bg_df[condition]

            BG2020     Variable  Interpolated  SETX  airsite_bg airsite_name
4862  482450051001  B25064_001E  Interpolated   1.0         1.0         W1.1
4863  482450051001  B25077_001E  Interpolated   1.0         1.0         W1.1
4864  482450051002  B25064_001E  Interpolated   1.0         1.0         W1.2
4872  482450059002  B25064_001E  Interpolated   1.0         1.0         W2.2
4873  482450059002  B25077_001E  Interpolated   1.0         1.0         W2.2
4878  482450066001  B25064_001E  Interpolated   1.0         1.0         E1.1

In [35]:
SVInsight_missing_bg_df[condition]['Variable'].unique()

array(['B25064_001E', 'B25077_001E'], dtype=object)

In [36]:
len(SVInsight_missing_bg_df[condition]['BG2020'].unique())

4

### Check Data Accuracy Using 2020 Tract Response Rates
https://www.census.gov/data/developers/data-sets/decennial-response-rates.html

CRRALL	Cumulative Self-Response Rate - Overall

In [37]:
crrall_url = "https://api.census.gov/data/2020/dec/responserate?get=NAME,GEO_ID,CRRALL&for=tract:*&in=state:48&in=county:*"
# Obtain Census API JSON Data
apijson = requests.get(crrall_url)
# Convert the requested json into pandas dataframe
crrall_df = pd.DataFrame(columns=apijson.json()[0], data=apijson.json()[1:])

In [38]:
crrall_df.head()

,NAME,GEO_ID,CRRALL,state,county,tract
0,"Census Tract 9501, Anderson County, Texas",1400000US48001950100,45.9,48,001,950100
1,"Census Tract 9504.01, Anderson County, Texas",1400000US48001950401,26.2,48,001,950401
2,"Census Tract 9504.02, Anderson County, Texas",1400000US48001950402,21.2,48,001,950402
3,"Census Tract 9505, Anderson County, Texas",1400000US48001950500,59.6,48,001,950500
4,"Census Tract 9506, Anderson County, Texas",1400000US48001950600,60.2,48,001,950600

In [39]:
Tract_df.head()

,TRACT2020,ALAND,AWATER,U202020010,U202020013,U202020020,U202020031,U202020033,U202020040,U202020070,...,H202081011,H202090012,H202090093,H202091012,H202091093,H202092021,SETX,FIPSCNTY,airsite_tract,airsite_name
0,48189950200,6306913,0,0.26355,0.29075,0.05352,-15052.0,-0.00000,-59500.0,537.0,...,0.36285,97.0,0.844,4.0,4.0,1.0,0.0,48189.0,0.0,NaN
1,48219950400,12691656,5302,0.21368,0.40714,0.10448,-16492.0,-0.00000,-43800.0,637.0,...,0.29107,93.6,0.796,4.0,4.0,1.0,0.0,48219.0,0.0,NaN
2,48219950300,12186639,0,0.23184,0.27081,0.05693,-26892.0,-0.02171,-98500.0,860.0,...,0.12183,74.7,0.643,3.0,3.0,1.0,0.0,48219.0,0.0,NaN
3,48219950100,214157569,0,0.13342,0.36347,0.08676,-20890.0,-0.01476,-60200.0,616.0,...,0.28967,80.9,0.686,4.0,4.0,1.0,0.0,48219.0,0.0,NaN
4,48219950600,358638163,0,0.11713,0.31648,0.01074,-34403.0,-0.09363,-97100.0,814.0,...,0.18914,40.9,0.445,2.0,2.0,1.0,0.0,48219.0,0.0,NaN

In [40]:
crrall_df['TRACT2020'] = crrall_df['GEO_ID'].str[-11:]
crrall_df['CRALL'] = crrall_df['CRRALL'].astype(float)
crrall_df['CRALL'].describe()

count    6774.000000
mean       62.122690
std        13.584122
min         4.800000
25%        53.100000
50%        62.600000
75%        72.400000
max        93.400000
Name: CRALL, dtype: float64

In [41]:
crrall_df.head()

,NAME,GEO_ID,CRRALL,state,county,tract,TRACT2020,CRALL
0,"Census Tract 9501, Anderson County, Texas",1400000US48001950100,45.9,48,001,950100,48001950100,45.9
1,"Census Tract 9504.01, Anderson County, Texas",1400000US48001950401,26.2,48,001,950401,48001950401,26.2
2,"Census Tract 9504.02, Anderson County, Texas",1400000US48001950402,21.2,48,001,950402,48001950402,21.2
3,"Census Tract 9505, Anderson County, Texas",1400000US48001950500,59.6,48,001,950500,48001950500,59.6
4,"Census Tract 9506, Anderson County, Texas",1400000US48001950600,60.2,48,001,950600,48001950600,60.2

In [42]:
# merge crrall_df with Tract_df on TRACT2020
Tract_df = Tract_df.merge(crrall_df[['TRACT2020','CRALL']], on='TRACT2020', how='left')
Tract_df.head()

,TRACT2020,ALAND,AWATER,U202020010,U202020013,U202020020,U202020031,U202020033,U202020040,U202020070,...,H202090012,H202090093,H202091012,H202091093,H202092021,SETX,FIPSCNTY,airsite_tract,airsite_name,CRALL
0,48189950200,6306913,0,0.26355,0.29075,0.05352,-15052.0,-0.00000,-59500.0,537.0,...,97.0,0.844,4.0,4.0,1.0,0.0,48189.0,0.0,NaN,50.7
1,48219950400,12691656,5302,0.21368,0.40714,0.10448,-16492.0,-0.00000,-43800.0,637.0,...,93.6,0.796,4.0,4.0,1.0,0.0,48219.0,0.0,NaN,47.2
2,48219950300,12186639,0,0.23184,0.27081,0.05693,-26892.0,-0.02171,-98500.0,860.0,...,74.7,0.643,3.0,3.0,1.0,0.0,48219.0,0.0,NaN,61.4
3,48219950100,214157569,0,0.13342,0.36347,0.08676,-20890.0,-0.01476,-60200.0,616.0,...,80.9,0.686,4.0,4.0,1.0,0.0,48219.0,0.0,NaN,46.2
4,48219950600,358638163,0,0.11713,0.31648,0.01074,-34403.0,-0.09363,-97100.0,814.0,...,40.9,0.445,2.0,2.0,1.0,0.0,48219.0,0.0,NaN,58.7

In [43]:
# print CRALL for airsite_name
condition = Tract_df['airsite_name'].isnull()
Tract_df[['airsite_name','CRALL']].loc[~condition]

     airsite_name  CRALL
1382           W2   54.9
1438           E1   51.9
2283           E2   62.4
3862           W1   34.7

### Save output as csv

In [44]:
# save as csv
table1_df_v3.to_csv(programname+"/"+programname+"_compare.csv", index=False)