# Setup SVI Option files
Combine all SVI option files to explore how SVI choices influence site selection.

## Description of Program
- program:    tu3svi4_2av4_SVIoptions
- task:       Create csv files with combined SVI options
- Version:    2025-04-08
- 2025-04-10  Focus on key variables and add highlight air site tracts
- 2025-04-12  Save merged version of SVI options for comparison
- 2025-04-16  Update name to SVInsight from UTP, keep area land and area water
- 2026-04-23  Minor updates in Replication Check
- project:    DOE Southeast Texas Urban Field Lab SVI Paper - round 4 of analysis 
- funding:	  DOE
- author:    Nathanael Rosenheim
- GRA:        Lidia Mezei

## Control Python
Add install and add packages.

In [1]:
import pandas as pd     # For obtaining and cleaning tabular data
import geopandas as gpd # For obtaining and cleaning spatial data
import numpy as np      # For working with arrays
import geopandas as gpd # For working with spatial data
import matplotlib.pyplot as plt # For plotting
import os # For saving to path

In [2]:
import sys
print("Python Version     ", sys.version)
print("geopandas version: ", gpd.__version__)

Python Version      3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
geopandas version:  1.1.1

## Set Provenance

In [3]:
# Get information on current working directory (getcwd)
os.getcwd()

'c:\\Users\\nathanael99\\Box\\SETx-UIFL_Team-folder\\Theme_3_eq\\Text\\SVI_Analysis_Paper\\DesignSafe-Archive\\Posted'

In [4]:
# Store Program Name for output files to have the same name and saved in the same directory
programname = "tu3svi4_2av2_SVIoptions_2026-04-23"
# Make directory to save output
if not os.path.exists(programname):
   os.mkdir(programname)

# Obtain Data

## 1.1 Obtain data from about each variable in SVI data.

In [5]:
# set data year
data_year = '2020'
geo_year = '2020' # geo year has to be 2010 or 2020

# dictionary of files to read in
SVI_files = {'SVInsight' : {'folderpath' : '../SourceData/UT_Preisser_SVI/',
                      'Tract' : f'tu3svi2_2av3_SetupUT_2025-04-08_Tract{data_year}.csv',
                      'BG'    : f'tu3svi2_2av3_SetupUT_2025-04-08_BG{data_year}.csv'},
             'CDC' : {'folderpath' : '../SourceData/www_atsdr_cdc_gov_placeandhealth_svi/',
                      'Tract' : f'tu3svi2_2bv2_SetupCDC_2024-09-06_Tract{data_year}.csv',
                      'BG'    : 'not available'},
             'HRRC': {'folderpath' : '../SourceData/texasatlas_arch_tamu_edu/',
                        'Tract' : f'tu3svi2_2cv3_SetupHRRC_2025-04-08_TractTX{data_year}.csv',
                        'BG'    : f'tu3svi2_2cv3_SetupHRRC_2025-04-08_BGTX{data_year}.csv'}
            }

In [6]:
# start empty dictionary to store dataframes
Tract_dfs = {}
BG_dfs    = {}
# loop over each SVI file
for SVI_file in SVI_files:
    print("Reading in SVI files for :",SVI_file)
    # Get file information
    folderpath = SVI_files[SVI_file]['folderpath']
    Tract_file = SVI_files[SVI_file]['Tract']
    BG_file    = SVI_files[SVI_file]['BG']
    # Read in Tract file
    if Tract_file != 'not available':
        Tract_dfs[SVI_file] = pd.read_csv(folderpath + Tract_file, dtype={f'TRACT{geo_year}': str})
    else:
        print('No Tract file available')
    # Read in BG file
    if BG_file != 'not available':
        BG_dfs[SVI_file] = pd.read_csv(folderpath + BG_file, dtype={f'BG{geo_year}': str})
    else:
        print('No block group file available')

Reading in SVI files for : SVInsight
Reading in SVI files for : CDC
No block group file available
Reading in SVI files for : HRRC

In [7]:
Tract_dfs['CDC'].head()

,TRACT2020,C202010020,C202010030,C202010040,C202020010,C202020020,C202020031,C202020050,C202021010,C202030010,...,C202090012,C202090021,C202090022,C202090031,C202090032,C202090091,C202090092,C202091011,C202091012,C202092023
0,01001020100,1941,693,710,0.181,0.021,0.208,0.096,0.143,0.152,...,NaN,0.2786,NaN,0.2397,NaN,0.0,NaN,2.0,NaN,NaN
1,01001020200,1757,573,720,0.254,0.040,0.260,0.059,0.106,0.162,...,NaN,0.4885,NaN,0.4721,NaN,1.0,NaN,3.0,NaN,NaN
2,01001020300,3694,1351,1464,0.228,0.027,0.195,0.035,0.128,0.126,...,NaN,0.4844,NaN,0.5055,NaN,0.0,NaN,3.0,NaN,NaN
3,01001020400,3539,1636,1741,0.142,0.024,0.174,0.048,0.062,0.274,...,NaN,0.2897,NaN,0.2836,NaN,1.0,NaN,2.0,NaN,NaN
4,01001020501,4306,1706,1786,0.210,0.010,0.206,0.032,0.088,0.126,...,NaN,0.3431,NaN,0.3514,NaN,0.0,NaN,2.0,NaN,NaN

In [8]:
BG_dfs['SVInsight'].head()

,BG2020,U202020010,U202020013,U202020020,U202020031,U202020033,U202020040,U202020070,U202021010,U202030020,...,U202065017,U202070010,U202070030,U202070040,U202070060,U202072010,U202020050,U202081021,U202081022,U202090012
0,484790019003,0.79026,0.83621,0.18750,-9939,-0.0,-71328,236,0.77470,1.20225,...,0.00000,0.0,0.35376,1.00000,1.04,0.79310,0.31692,0.53846,0.00000,1.00000
1,481130166351,0.32397,0.85294,0.45000,-16472,-0.0,-208910,792,0.14419,1.76966,...,1.00000,0.0,0.05179,1.00000,1.12,0.41597,0.19879,0.00000,0.00000,0.99995
2,480610140012,0.72041,0.64715,0.00000,-8749,-0.0,-49878,270,0.74402,1.03776,...,0.45635,0.0,0.04206,0.95285,1.59,0.66829,0.22415,0.52381,0.12302,0.99989
3,481130162031,0.48011,0.42690,0.50242,-15051,-0.0,-133834,973,0.56322,1.17241,...,0.27184,0.0,0.10236,1.00000,1.10,0.86550,0.27012,0.33981,0.00000,0.99984
4,482150205072,0.86572,0.72857,0.00000,0,-0.0,-87253,1011,0.80000,1.03180,...,1.00000,0.0,0.00000,0.00000,2.02,0.00000,0.30998,0.00000,0.00000,0.99978

In [9]:
BG_dfs['HRRC'].head()

,BG2020,H202010020,H202010030,H202020010,H202020012,H202020020,H202020040,H202021010,H202030011,H202033010,...,H202070040,H202070070,H202072010,H202072020,H202081011,H202090012,H202090093,H202091012,H202091093,H202092021
0,480019501001,1640,608,0.14357,0.05428,0.14403,301900,0.17266,0.31579,0.19572,...,0.21505,0.78360,0.05428,0.0,0.23026,0.886,0.735,4.0,4.0,1.0
1,480019501002,1901,626,0.13793,0.02396,0.07344,262600,0.04793,0.29872,0.02875,...,0.14308,0.61001,0.00000,0.0,0.17732,0.457,0.464,2.0,2.0,1.0
2,480019501003,1417,545,0.26464,0.00000,0.00000,305500,0.03950,0.30275,0.12477,...,0.12562,0.66102,0.01101,0.0,0.27156,0.312,0.386,2.0,2.0,1.0
3,480019504011,4867,81,0.00000,0.00000,0.00000,275000,0.26896,0.08642,0.08642,...,0.66667,0.86000,0.00000,0.0,0.17284,0.229,0.336,1.0,1.0,1.0
4,480019504021,7335,0,1.00000,0.00000,0.00000,271100,0.29417,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.0,0.00000,0.016,0.102,1.0,1.0,1.0

In [10]:
### Merge dataframes
# loop through data frames in Tract_dfs and merge together on TRACT2010
print("Merging Tract dataframes")
Tract_df = pd.DataFrame()
for SVI_file in Tract_dfs:
    print("Merging :",SVI_file)
    if Tract_df.empty:
        Tract_df = Tract_dfs[SVI_file]
    else:
        Tract_df = Tract_df.merge(Tract_dfs[SVI_file], on=f'TRACT{data_year}', how='outer')

Merging Tract dataframes
Merging : SVInsight
Merging : CDC
Merging : HRRC

In [11]:
# loop through data frames in Block group and merge together on BG2010
print("Merging Block Group dataframes")
BG_df = pd.DataFrame()
for SVI_file in BG_dfs:
    print("Merging :",SVI_file)
    if BG_df.empty:
        BG_df = BG_dfs[SVI_file]
    else:
        BG_df = BG_df.merge(BG_dfs[SVI_file], on=f'BG{data_year}', how='outer')

Merging Block Group dataframes
Merging : SVInsight
Merging : HRRC

In [12]:
# keep texas tracts only 
condition = Tract_df['TRACT2020'].str.startswith('48')
Tract_df = Tract_df[condition]
Tract_df['TRACT2020'].describe().T

count            6884
unique           6884
top       48001950100
freq                1
Name: TRACT2020, dtype: object

In [13]:
BG_df['BG2020'].describe().T

count            18626
unique           18626
top       480019501001
freq                 1
Name: BG2020, dtype: object

In [14]:
# keep texas BG only 
condition = BG_df['BG2020'].str.startswith('48')
BG_df = BG_df[condition]
BG_df['BG2020'].describe().T

count            18626
unique           18626
top       480019501001
freq                 1
Name: BG2020, dtype: object

In [15]:
# Create a new variable for Southeast Texas Counties 
# County dictionary
setx_county_dict = {    
    '48245' : 'Jefferson', 
    '48361' : 'Orange', 
    '48199' : 'Hardin', 
    '48241' : 'Jasper', 
    '48351' : 'Newton'
    }
# Create a new variable for Southeast Texas Counties
# If county is in dictionary set variable = 1
BG_df['SETX'] = 0
# replace SETX = 1 if county is in dictionary
BG_df['FIPSCNTY'] = BG_df[f'BG{geo_year}'].str[:5]
condition = BG_df['FIPSCNTY'].isin(setx_county_dict.keys())
BG_df.loc[condition, 'SETX'] = 1
# check variable group SETX by county
BG_df['SETX'].describe()

count    18626.000000
mean         0.019704
std          0.138984
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: SETX, dtype: float64

In [16]:
# check coutines SETX
condition = BG_df['SETX'] == 1
# group by county
BG_df[condition].groupby('FIPSCNTY').size()

FIPSCNTY
48199     41
48241     28
48245    215
48351     14
48361     69
dtype: int64

In [17]:
# Create a new variable for Southeast Texas Counties
# If county is in dictionary set variable = 1
Tract_df['SETX'] = 0
# replace SETX = 1 if county is in dictionary
Tract_df['FIPSCNTY'] = Tract_df[f'TRACT{geo_year}'].str[:5]
condition = Tract_df['FIPSCNTY'].isin(setx_county_dict.keys())
Tract_df.loc[condition, 'SETX'] = 1
# check variable group SETX by county
Tract_df['SETX'].describe()

count    6884.000000
mean        0.018594
std         0.135095
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: SETX, dtype: float64

In [18]:
# check coutines SETX
condition = Tract_df['SETX'] == 1
# group by county
Tract_df[condition].groupby('FIPSCNTY').size()

FIPSCNTY
48199    13
48241    10
48245    76
48351     5
48361    24
dtype: int64

# Clean Data
Need to have one data frame with all three SVI options.

For now just keep the SVI score.

## 2.1 Clean up SVI data

In [19]:
# Keep TRACT ID and SVI score
# CDC has percentile rank for US and Texas, keep population, households, and housing unit totals 
svi_keepvars = [f'TRACT{geo_year}','FIPSCNTY', 'SETX',
                f'C{data_year}10020', # GEOID and Total Population
                f'C{data_year}90012',
                f'H{data_year}90012',
                f'U{data_year}90012']

# Keep Block Group ID and SVI score
svi_keepvars = [f'BG{geo_year}','FIPSCNTY','SETX', f'H{data_year}90012',
                                 f'U{data_year}90012']

In [20]:
# convert SVI Scores to Percent (0-100)
Tract_df[f'C{data_year}90012'] = Tract_df[f'C{data_year}90012']*100
Tract_df[f'H{data_year}90012'] = Tract_df[f'H{data_year}90012']*100
Tract_df[f'U{data_year}90012'] = Tract_df[f'U{data_year}90012']*100

# convert SVI Scores to Percent (0-100)
BG_df[f'H{data_year}90012'] = BG_df[f'H{data_year}90012']*100
BG_df[f'U{data_year}90012'] = BG_df[f'U{data_year}90012']*100

# Create TRACT ID from BG ID by removing the last digit
BG_df[f'TRACT{geo_year}'] = BG_df[f'BG{geo_year}'].str[:-1]

### Flag Observations in Air Sites

Four Census Tracts
- West Side of Port Arthur: 48245005100, 48245005900
- East Groves: 48245006600, 48245010600

In [21]:
# Create a new variable for air site tracts
# tract dictionary
airsite_tract_dict = {    
    '48245005100' : 'W1', 
    '48245005900' : 'W2', 
    '48245006600' : 'E1', 
    '48245010600' : 'E2'
    }
# Create a new variable for Air Site Tracts
# If tract is in dictionary set variable = 1
Tract_df['airsite_tract'] = 0
condition = Tract_df['TRACT2020'].isin(airsite_tract_dict.keys())
Tract_df.loc[condition, 'airsite_tract'] = 1
# use dictionary to assign air site name
Tract_df['airsite_name'] = ''
Tract_df.loc[condition, 'airsite_name'] = Tract_df['TRACT2020'].map(airsite_tract_dict)
# check variable group SETX by county
Tract_df['airsite_tract'].describe()

count    6884.000000
mean        0.000581
std         0.024100
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: airsite_tract, dtype: float64

In [22]:
# group by air site name and count
Tract_df.groupby('airsite_name')['airsite_tract'].describe()

               count  mean  std  min  25%  50%  75%  max
airsite_name
              6880.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
E1               1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
E2               1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
W1               1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
W2               1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0

In [23]:
# Create a new variable for air site bg
# block group dictionary
airsite_bg_dict = {    
    '482450051001' : 'W1.1', 
    '482450051002' : 'W1.2', 
    '482450059001' : 'W2.1', 
    '482450059002' : 'W2.2', 
    '482450066001' : 'E1.1', 
    '482450106005' : 'E2.1',
    }
# Create a new variable for Air Site Tracts
# If tract is in dictionary set variable = 1
BG_df['airsite_bg'] = 0
condition = BG_df['BG2020'].isin(airsite_bg_dict.keys())
BG_df.loc[condition, 'airsite_bg'] = 1
# use dictionary to assign air site name
BG_df['airsite_name'] = ''
BG_df.loc[condition, 'airsite_name'] = BG_df['BG2020'].map(airsite_bg_dict)
# check variable group SETX by county
BG_df['airsite_bg'].describe()

count    18626.000000
mean         0.000322
std          0.017946
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: airsite_bg, dtype: float64

In [24]:
# group by air site name and count
BG_df.groupby('airsite_name')['airsite_bg'].describe()

                count  mean  std  min  25%  50%  75%  max
airsite_name
              18620.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
E1.1              1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
E2.1              1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
W1.1              1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
W1.2              1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
W2.1              1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0
W2.2              1.0   1.0  NaN  1.0  1.0  1.0  1.0  1.0

### Add Area Land and Water

In [25]:
### Read in 2020 tract shapefile
sourcefolder = "../SourceData/www2_census_gov/tl_2020_48_tract"
sourcefile = "tl_2020_48_tract.shp"
file_path = os.path.join(sourcefolder, sourcefile)
tx_2020_tract_gdf = gpd.read_file(file_path)
# keep geoid and geometry
tx_2020_tract_gdf = tx_2020_tract_gdf[[f'GEOID', 'geometry','ALAND','AWATER']].copy(deep=True)
# rename geoid to BG2020
tx_2020_tract_gdf.rename(columns={'GEOID': f'TRACT{geo_year}'}, inplace=True)
# convert geoid to string
tx_2020_tract_gdf[f'TRACT{geo_year}'] = tx_2020_tract_gdf[f'TRACT{geo_year}'].astype(str)
# merge tract and SVI data
Tract_gdf = pd.merge(tx_2020_tract_gdf, Tract_df, on=f'TRACT{geo_year}', how='left')
Tract_gdf.head()

,TRACT2020,geometry,ALAND,AWATER,U202020010,U202020013,U202020020,U202020031,U202020033,U202020040,...,H202081011,H202090012,H202090093,H202091012,H202091093,H202092021,SETX,FIPSCNTY,airsite_tract,airsite_name
0,48189950200,"POLYGON ((-101.74 34.211, -101.74 34.211, -101...",6306913,0,0.26355,0.29075,0.05352,-15052.0,-0.00000,-59500.0,...,0.36285,97.0,0.844,4.0,4.0,1.0,0.0,48189,0.0,
1,48219950400,"POLYGON ((-102.42 33.57, -102.42 33.57, -102.4...",12691656,5302,0.21368,0.40714,0.10448,-16492.0,-0.00000,-43800.0,...,0.29107,93.6,0.796,4.0,4.0,1.0,0.0,48219,0.0,
2,48219950300,"POLYGON ((-102.37 33.584, -102.37 33.584, -102...",12186639,0,0.23184,0.27081,0.05693,-26892.0,-0.02171,-98500.0,...,0.12183,74.7,0.643,3.0,3.0,1.0,0.0,48219,0.0,
3,48219950100,"POLYGON ((-102.28 33.724, -102.28 33.725, -102...",214157569,0,0.13342,0.36347,0.08676,-20890.0,-0.01476,-60200.0,...,0.28967,80.9,0.686,4.0,4.0,1.0,0.0,48219,0.0,
4,48219950600,"POLYGON ((-102.32 33.41, -102.32 33.41, -102.3...",358638163,0,0.11713,0.31648,0.01074,-34403.0,-0.09363,-97100.0,...,0.18914,40.9,0.445,2.0,2.0,1.0,0.0,48219,0.0,

In [26]:
### Read in 2020 BG shapefile
sourcefolder = "../SourceData/www2_census_gov/tl_2020_48_bg"
sourcefile = "tl_2020_48_bg.shp"
file_path = os.path.join(sourcefolder, sourcefile)
tx_2020_bg_gdf = gpd.read_file(file_path)
# keep geoid and geometry
tx_2020_bg_gdf = tx_2020_bg_gdf[[f'GEOID', 'geometry','ALAND','AWATER']].copy(deep=True)
# rename geoid to BG2020
tx_2020_bg_gdf.rename(columns={'GEOID': f'BG{geo_year}'}, inplace=True)
# convert geoid to string
tx_2020_bg_gdf[f'BG{geo_year}'] = tx_2020_bg_gdf[f'BG{geo_year}'].astype(str)
# merge bg and SVI data
BG_gdf = pd.merge(tx_2020_bg_gdf, BG_df, on=f'BG{geo_year}', how='left')
BG_gdf.head()

,BG2020,geometry,ALAND,AWATER,U202020010,U202020013,U202020020,U202020031,U202020033,U202020040,...,H202090012,H202090093,H202091012,H202091093,H202092021,SETX,FIPSCNTY,TRACT2020,airsite_bg,airsite_name
0,481539506003,"POLYGON ((-101.38 33.984, -101.38 33.985, -101...",9238641,0,0.12273,0.59882,0.02113,-41060.0,-0.02360,-73300.0,...,72.0,0.613,3.0,3.0,1.0,0.0,48153,48153950600,0.0,
1,481539506005,"POLYGON ((-101.56 34.06, -101.56 34.06, -101.5...",1070676551,101332,0.33274,0.08228,0.00000,-22793.0,-0.06962,-163500.0,...,22.6,0.334,1.0,1.0,1.0,0.0,48153,48153950600,0.0,
2,481610004001,"POLYGON ((-96.496 31.796, -96.496 31.797, -96....",12766486,8204,0.30405,0.36973,0.05444,-17938.0,-0.00000,-78900.0,...,82.9,0.689,4.0,4.0,1.0,0.0,48161,48161000400,0.0,
3,481610006001,"POLYGON ((-96.421 31.686, -96.421 31.686, -96....",153883256,544987,0.00000,0.50709,0.00000,-27873.0,-0.14894,-153900.0,...,27.6,0.365,2.0,2.0,1.0,0.0,48161,48161000600,0.0,
4,481759602001,"POLYGON ((-97.654 28.754, -97.654 28.755, -97....",391287006,1789495,0.18392,0.56607,0.01743,-32928.0,-0.07495,-157900.0,...,53.0,0.502,3.0,3.0,1.0,0.0,48175,48175960200,0.0,

# Save Results

In [27]:
# save to csv
outputfile = os.path.join(programname, f'{programname}_all_vars_tract2020.csv')
# save without the geometry column
Tract_gdf.drop(columns=['geometry']).to_csv(outputfile, index=False)

In [28]:
# save to csv
outputfile = os.path.join(programname, f'{programname}_all_vars_bg2020.csv')
BG_gdf.drop(columns=['geometry']).to_csv(outputfile, index=False)

In [29]:
# keep just the variables we want
keep_vars_bg = [f'BG{geo_year}', f'TRACT{geo_year}', 'FIPSCNTY', 'SETX', f'H{data_year}90012', f'U{data_year}90012',
                 'airsite_bg', 'airsite_name']
BG_gdf[keep_vars_bg].head()

,BG2020,TRACT2020,FIPSCNTY,SETX,H202090012,U202090012,airsite_bg,airsite_name
0,481539506003,48153950600,48153,0.0,72.0,79.840,0.0,
1,481539506005,48153950600,48153,0.0,22.6,17.038,0.0,
2,481610004001,48161000400,48161,0.0,82.9,90.819,0.0,
3,481610006001,48161000600,48161,0.0,27.6,63.650,0.0,
4,481759602001,48175960200,48175,0.0,53.0,76.442,0.0,

In [30]:
# save to csv
outputfile = os.path.join(programname, f'{programname}_bg2020.csv')
BG_gdf[keep_vars_bg].to_csv(outputfile, index=False)

In [31]:
# keep just the variables we want
keep_vars_tract = [f'TRACT{geo_year}', 'FIPSCNTY', 'SETX', 
                f'C{data_year}90012', f'H{data_year}90012', f'U{data_year}90012',
                 'airsite_tract', 'airsite_name']
Tract_gdf[keep_vars_tract].head()

,TRACT2020,FIPSCNTY,SETX,C202090012,H202090012,U202090012,airsite_tract,airsite_name
0,48189950200,48189,0.0,93.60,97.0,89.377,0.0,
1,48219950400,48219,0.0,96.48,93.6,92.879,0.0,
2,48219950300,48219,0.0,77.90,74.7,72.762,0.0,
3,48219950100,48219,0.0,65.75,80.9,83.971,0.0,
4,48219950600,48219,0.0,44.65,40.9,70.022,0.0,

In [32]:
# save to csv
outputfile = os.path.join(programname, f'{programname}_tract2020.csv')
Tract_gdf[keep_vars_tract].to_csv(outputfile, index=False)

### Save as Geodataframe

In [33]:
# save just SETX counties to shapefile
condition = Tract_gdf['SETX'] == 1
outputfile = os.path.join(programname, f'{programname}_tract2020_SETX.shp')
Tract_gdf[condition].to_file(outputfile, driver='ESRI Shapefile')

C:\Users\nathanael99\AppData\Local\Temp\ipykernel_5644\3224023211.py:4: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  Tract_gdf[condition].to_file(outputfile, driver='ESRI Shapefile')
c:\Users\nathanael99\AppData\Local\miniconda3\envs\pyncoda20251203\lib\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'airsite_tract' to 'airsite_tr'
  ogr_write(
c:\Users\nathanael99\AppData\Local\miniconda3\envs\pyncoda20251203\lib\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'airsite_name' to 'airsite_na'
  ogr_write(

In [34]:
# save just SETX counties to shapefile
condition = BG_gdf['SETX'] == 1
outputfile = os.path.join(programname, f'{programname}_bg2020_SETX.shp')
BG_gdf[condition].to_file(outputfile, driver='ESRI Shapefile')

C:\Users\nathanael99\AppData\Local\Temp\ipykernel_5644\3216869819.py:4: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  BG_gdf[condition].to_file(outputfile, driver='ESRI Shapefile')
c:\Users\nathanael99\AppData\Local\miniconda3\envs\pyncoda20251203\lib\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'airsite_name' to 'airsite_na'
  ogr_write(

## Generate Codebook
https://github.com/npr99/pypdfcodebook

In [35]:
from pypdfcodebook.pdfcb_03c_codebook import codebook

In [36]:
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path

filename = "tu3svi2_0bv1_SVIdatadictionary_2026-04-23_datastructure.py"
file_path = Path("../SourceData/") / filename

# Run .py code to get the base data structure.
spec = spec_from_file_location("svi_ds", file_path)
svi_ds = module_from_spec(spec)
spec.loader.exec_module(svi_ds)

# Copy and align data structure to dataframe columns.
datastructure = dict(svi_ds.DATA_STRUCTURE)

datastructure_bg, compare_df = svi_ds.match_data_structure_to_df(
    datastructure=datastructure,
    df=BG_df
    )

# Copy and align data structure to dataframe columns.
datastructure = dict(svi_ds.DATA_STRUCTURE)

datastructure_tract, compare_df = svi_ds.match_data_structure_to_df(
    datastructure=datastructure,
    df=Tract_df
    )

In [37]:
codebook_output_folders = {"top": programname}

In [38]:
cb = codebook(
    input_df=BG_df,
    header_title="SVI Analysis: Block Group Level Data",
    datastructure=datastructure_bg,
    projectoverview="../README.md",
    keyterms='',
    output_filename=f"{programname}_all_vars_bg2020_codebook",
    outputfolders=codebook_output_folders,
 )

# Generate the PDF codebook
cb.create_codebook()

Creating codebook: SVI Analysis: Block Group Level Data
Saving codebook to tu3svi4_2av2_SVIoptions_2026-04-23/tu3svi4_2av2_SVIoptions_2026-04-23_all_vars_bg2020_codebook.pdf

In [39]:
cb = codebook(
    input_df=Tract_df,
    header_title="SVI Analysis: Tract Level Data",
    datastructure=datastructure_tract,
    projectoverview="../README.md",
    keyterms='',
    output_filename=f"{programname}_all_vars_tract2020_codebook",
    outputfolders=codebook_output_folders,
 )

# Generate the PDF codebook
cb.create_codebook()

Creating codebook: SVI Analysis: Tract Level Data
Saving codebook to tu3svi4_2av2_SVIoptions_2026-04-23/tu3svi4_2av2_SVIoptions_2026-04-23_all_vars_tract2020_codebook.pdf